server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    client_max_body_size 1m;
    location /portal/ { proxy_pass http://public-api:8011; }
    location / { try_files $uri $uri/ /index.html; }
}
