server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    client_max_body_size 2m;
    location /admin/ { proxy_pass http://admin-api:8012; }
    location / { try_files $uri $uri/ /index.html; }
}
