GENERAL_STORYBOARD_MAX_SHOTS = 17
GENERAL_STORYBOARD_MAX_GROUPS = 10
OUTLINE_STALE_SECONDS = 150
OUTLINE_WATCH_TIMEOUT_SECONDS = 300
STORYBOARD_LINE_TIMEOUT_SECONDS = 12 * 60
SHORT_LYRIC_MERGE_SECONDS = 5.0
INTERLUDE_GAP_SECONDS = 2.0
