"""multi user persistence and soft delete

Revision ID: d668fb1d8c09
Revises: 0001_initial
Create Date: 2026-08-06 23:43:31.028149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd668fb1d8c09'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('digital_human_styles',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_dh_style_user_name')
    )
    op.create_index(op.f('ix_digital_human_styles_deleted_at'), 'digital_human_styles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_digital_human_styles_scope'), 'digital_human_styles', ['scope'], unique=False)
    op.create_index(op.f('ix_digital_human_styles_user_id'), 'digital_human_styles', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('song_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_deleted_at'), 'refresh_tokens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('digital_humans',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('style_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('avatar_prompt', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['digital_human_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_humans_deleted_at'), 'digital_humans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_digital_humans_scope'), 'digital_humans', ['scope'], unique=False)
    op.create_index(op.f('ix_digital_humans_style_id'), 'digital_humans', ['style_id'], unique=False)
    op.create_index(op.f('ix_digital_humans_user_id'), 'digital_humans', ['user_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('storyboard_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_ass_url', sa.Text(), nullable=True),
    sa.Column('extra_requirement', sa.Text(), nullable=False),
    sa.Column('overall_prompt', sa.Text(), nullable=False),
    sa.Column('storyboard_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tasks_deleted_at'), 'project_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_project_tasks_storyboard_type'), 'project_tasks', ['storyboard_type'], unique=False)
    op.create_table('material_exports',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('project_task_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_exports_deleted_at'), 'material_exports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_material_exports_project_task_id'), 'material_exports', ['project_task_id'], unique=False)
    op.create_index(op.f('ix_material_exports_user_id'), 'material_exports', ['user_id'], unique=False)
    op.create_table('project_cast',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_task_id', sa.String(length=80), nullable=False),
    sa.Column('digital_human_id', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['digital_human_id'], ['digital_humans.id'], ),
    sa.ForeignKeyConstraint(['project_task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_task_id', 'digital_human_id', name='uq_task_cast_human')
    )
    op.create_index(op.f('ix_project_cast_deleted_at'), 'project_cast', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_cast_digital_human_id'), 'project_cast', ['digital_human_id'], unique=False)
    op.create_index(op.f('ix_project_cast_project_task_id'), 'project_cast', ['project_task_id'], unique=False)
    op.create_table('storyboard_lines',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_task_id', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('shot_type', sa.String(length=32), nullable=True),
    sa.Column('planned_duration', sa.Float(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('lyrics_zh', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('scene_prompt', sa.Text(), nullable=False),
    sa.Column('shot_prompt', sa.Text(), nullable=False),
    sa.Column('shot_options', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboard_lines_deleted_at'), 'storyboard_lines', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_storyboard_lines_project_task_id'), 'storyboard_lines', ['project_task_id'], unique=False)
    op.create_table('storyboard_line_cast',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('storyboard_line_id', sa.String(length=80), nullable=False),
    sa.Column('digital_human_id', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['digital_human_id'], ['digital_humans.id'], ),
    sa.ForeignKeyConstraint(['storyboard_line_id'], ['storyboard_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_line_id', 'digital_human_id', name='uq_line_cast_human')
    )
    op.create_index(op.f('ix_storyboard_line_cast_deleted_at'), 'storyboard_line_cast', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_storyboard_line_cast_digital_human_id'), 'storyboard_line_cast', ['digital_human_id'], unique=False)
    op.create_index(op.f('ix_storyboard_line_cast_storyboard_line_id'), 'storyboard_line_cast', ['storyboard_line_id'], unique=False)
    op.create_table('scene_assets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('storyboard_line_id', sa.String(length=80), nullable=False),
    sa.Column('generation_job_id', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['storyboard_line_id'], ['storyboard_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_assets_deleted_at'), 'scene_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_scene_assets_storyboard_line_id'), 'scene_assets', ['storyboard_line_id'], unique=False)
    op.create_table('shot_assets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('storyboard_line_id', sa.String(length=80), nullable=False),
    sa.Column('generation_job_id', sa.String(length=80), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('ratio', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['storyboard_line_id'], ['storyboard_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_assets_deleted_at'), 'shot_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shot_assets_storyboard_line_id'), 'shot_assets', ['storyboard_line_id'], unique=False)
    op.create_table('voice_assets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('storyboard_line_id', sa.String(length=80), nullable=False),
    sa.Column('generation_job_id', sa.String(length=80), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('voice_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['storyboard_line_id'], ['storyboard_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_assets_deleted_at'), 'voice_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_voice_assets_storyboard_line_id'), 'voice_assets', ['storyboard_line_id'], unique=False)
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_messages_deleted_at'), 'chat_messages', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(length=80), nullable=True))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_sessions_deleted_at'), 'chat_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.add_column('generation_jobs', sa.Column('user_id', sa.String(length=80), nullable=True))
    op.add_column('generation_jobs', sa.Column('project_id', sa.String(length=80), nullable=True))
    op.add_column('generation_jobs', sa.Column('project_task_id', sa.String(length=80), nullable=True))
    op.add_column('generation_jobs', sa.Column('storyboard_line_id', sa.String(length=80), nullable=True))
    op.add_column('generation_jobs', sa.Column('provider', sa.String(length=80), nullable=True))
    op.add_column('generation_jobs', sa.Column('provider_task_id', sa.String(length=160), nullable=True))
    op.add_column('generation_jobs', sa.Column('attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('generation_jobs', sa.Column('idempotency_key', sa.String(length=160), nullable=True))
    op.add_column('generation_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('generation_jobs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('generation_jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_generation_jobs_deleted_at'), 'generation_jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generation_jobs_idempotency_key'), 'generation_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_generation_jobs_project_id'), 'generation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_project_task_id'), 'generation_jobs', ['project_task_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_storyboard_line_id'), 'generation_jobs', ['storyboard_line_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'generation_jobs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'generation_jobs', 'storyboard_lines', ['storyboard_line_id'], ['id'])
    op.create_foreign_key(None, 'generation_jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'generation_jobs', 'project_tasks', ['project_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_generation_jobs_user_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_storyboard_line_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_project_task_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_project_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_idempotency_key'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_deleted_at'), table_name='generation_jobs')
    op.drop_column('generation_jobs', 'deleted_at')
    op.drop_column('generation_jobs', 'finished_at')
    op.drop_column('generation_jobs', 'started_at')
    op.drop_column('generation_jobs', 'idempotency_key')
    op.drop_column('generation_jobs', 'attempt')
    op.drop_column('generation_jobs', 'provider_task_id')
    op.drop_column('generation_jobs', 'provider')
    op.drop_column('generation_jobs', 'storyboard_line_id')
    op.drop_column('generation_jobs', 'project_task_id')
    op.drop_column('generation_jobs', 'project_id')
    op.drop_column('generation_jobs', 'user_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_deleted_at'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'user_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_deleted_at'), table_name='chat_messages')
    op.drop_column('chat_messages', 'deleted_at')
    op.drop_column('chat_messages', 'updated_at')
    op.drop_index(op.f('ix_voice_assets_storyboard_line_id'), table_name='voice_assets')
    op.drop_index(op.f('ix_voice_assets_deleted_at'), table_name='voice_assets')
    op.drop_table('voice_assets')
    op.drop_index(op.f('ix_shot_assets_storyboard_line_id'), table_name='shot_assets')
    op.drop_index(op.f('ix_shot_assets_deleted_at'), table_name='shot_assets')
    op.drop_table('shot_assets')
    op.drop_index(op.f('ix_scene_assets_storyboard_line_id'), table_name='scene_assets')
    op.drop_index(op.f('ix_scene_assets_deleted_at'), table_name='scene_assets')
    op.drop_table('scene_assets')
    op.drop_index(op.f('ix_storyboard_line_cast_storyboard_line_id'), table_name='storyboard_line_cast')
    op.drop_index(op.f('ix_storyboard_line_cast_digital_human_id'), table_name='storyboard_line_cast')
    op.drop_index(op.f('ix_storyboard_line_cast_deleted_at'), table_name='storyboard_line_cast')
    op.drop_table('storyboard_line_cast')
    op.drop_index(op.f('ix_storyboard_lines_project_task_id'), table_name='storyboard_lines')
    op.drop_index(op.f('ix_storyboard_lines_deleted_at'), table_name='storyboard_lines')
    op.drop_table('storyboard_lines')
    op.drop_index(op.f('ix_project_cast_project_task_id'), table_name='project_cast')
    op.drop_index(op.f('ix_project_cast_digital_human_id'), table_name='project_cast')
    op.drop_index(op.f('ix_project_cast_deleted_at'), table_name='project_cast')
    op.drop_table('project_cast')
    op.drop_index(op.f('ix_material_exports_user_id'), table_name='material_exports')
    op.drop_index(op.f('ix_material_exports_project_task_id'), table_name='material_exports')
    op.drop_index(op.f('ix_material_exports_deleted_at'), table_name='material_exports')
    op.drop_table('material_exports')
    op.drop_index(op.f('ix_project_tasks_storyboard_type'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_deleted_at'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_digital_humans_user_id'), table_name='digital_humans')
    op.drop_index(op.f('ix_digital_humans_style_id'), table_name='digital_humans')
    op.drop_index(op.f('ix_digital_humans_scope'), table_name='digital_humans')
    op.drop_index(op.f('ix_digital_humans_deleted_at'), table_name='digital_humans')
    op.drop_table('digital_humans')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_deleted_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_digital_human_styles_user_id'), table_name='digital_human_styles')
    op.drop_index(op.f('ix_digital_human_styles_scope'), table_name='digital_human_styles')
    op.drop_index(op.f('ix_digital_human_styles_deleted_at'), table_name='digital_human_styles')
    op.drop_table('digital_human_styles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
