"""partial unique indexes for soft delete

Revision ID: fb942da7380f
Revises: d668fb1d8c09
Create Date: 2026-08-06 23:46:00.914997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb942da7380f'
down_revision: Union[str, None] = 'd668fb1d8c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_dh_style_user_name'), 'digital_human_styles', type_='unique')
    op.create_index('uq_dh_style_user_name_active', 'digital_human_styles', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_task_cast_human'), 'project_cast', type_='unique')
    op.create_index('uq_task_cast_human_active', 'project_cast', ['project_task_id', 'digital_human_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_line_cast_human'), 'storyboard_line_cast', type_='unique')
    op.create_index('uq_line_cast_human_active', 'storyboard_line_cast', ['storyboard_line_id', 'digital_human_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_line_cast_human_active', table_name='storyboard_line_cast', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_line_cast_human'), 'storyboard_line_cast', ['storyboard_line_id', 'digital_human_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_task_cast_human_active', table_name='project_cast', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_task_cast_human'), 'project_cast', ['project_task_id', 'digital_human_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_dh_style_user_name_active', table_name='digital_human_styles', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_dh_style_user_name'), 'digital_human_styles', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
