export const GENERAL_STORYBOARD_MAX_SHOTS = 17
export const GENERAL_STORYBOARD_MAX_GROUPS = 10
export const OUTLINE_WATCH_TIMEOUT_MS = 300_000
export const STORYBOARD_LINE_REFRESH_AFTER_MS = 60_000
export const STORYBOARD_LINE_WAIT_TIMEOUT_MS = 13 * 60_000
