// Isolated databases and processes; no supplier keys and no worker/model requests.
import { chromium, expect } from '@playwright/test'
import { spawn, spawnSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const python=path.resolve(root,'../backend/.venv/bin/python')
const run=randomUUID()
const dbPath=path.join(root,'.runtime',`portal-browser-${run}.db`)
const minimal={PATH:process.env.PATH,HOME:process.env.HOME,TMPDIR:process.env.TMPDIR}
const env={...minimal,DATABASE_URL:'sqlite+aiosqlite:///'+dbPath,ADMIN_JWT_SECRET:randomUUID()+randomUUID(),ADMIN_USERNAME:'admin',ADMIN_PASSWORD:randomUUID()}
function command(args,extra={}){const r=spawnSync(python,args,{cwd:root,env:{...env,...extra},encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);return r.stdout}
command(['-m','alembic','upgrade','head'])
command(['scripts/seed.py'],{PYTHONPATH:path.join(root,'public-api')})
command(['-c', `import asyncio
from gateway.db import Model, ModelRoute, Session, now
from sqlalchemy import select
async def run():
 async with Session.begin() as db:
  for route in (await db.scalars(select(ModelRoute))).all(): route.deleted_at=now()
  model=await db.get(Model,'gpt-5.6-sol')
  model.enabled=True
  model.capabilities={"unified_catalog":True,"catalog_selected":True}
  db.add(ModelRoute(id='quote-browser-route',model_id='gpt-5.6-sol',supplier='yseeai',channel='yseeai-llm',provider_model='gpt-5.6-sol',protocol='chat',enabled=False,priority=10,concurrency=1,verification='pending',capabilities={},pricing={'estimate_rules':[]}))
asyncio.run(run())`],{PYTHONPATH:path.join(root,'public-api')})
const processes=[]
function start(cmd,args,cwd,vars){const fd=fs.openSync(path.join(root,'.runtime','portal-browser-process.log'),'a');const p=spawn(cmd,args,{cwd,env:vars,stdio:['ignore',fd,fd],detached:true});processes.push(p);fs.closeSync(fd)}
async function ready(url){for(let i=0;i<80;i++){try{if((await fetch(url)).ok)return}catch{}await new Promise(r=>setTimeout(r,250))}throw Error('Service not ready: '+url)}
let browser
try {
 start(python,['-m','uvicorn','gateway.main:app','--port','8191'],path.join(root,'public-api'),{...minimal,DATABASE_URL:env.DATABASE_URL})
 start(python,['-m','uvicorn','control.main:app','--port','8192'],path.join(root,'admin-api'),env)
 start('npm',['run','dev','--','--port','8193'],path.join(root,'admin-web'),{...minimal,ADMIN_API_TARGET:'http://127.0.0.1:8192'})
 start('npm',['run','dev','--','--port','8194'],path.join(root,'user-web'),{...minimal,PUBLIC_API_TARGET:'http://127.0.0.1:8191'})
 await Promise.all(['http://127.0.0.1:8191/health','http://127.0.0.1:8192/health','http://127.0.0.1:8193','http://127.0.0.1:8194'].map(ready))
 browser=await chromium.launch({headless:true})
 const user=await browser.newPage({viewport:{width:1440,height:1000}})
 const admin=await browser.newPage({viewport:{width:1440,height:1100}})
 user.setDefaultTimeout(15000);admin.setDefaultTimeout(15000)
 const errors=[];for(const p of [user,admin])p.on('pageerror',e=>errors.push(e.message))
 await admin.goto('http://127.0.0.1:8193')
 await admin.getByLabel('用户名',{exact:true}).fill('admin')
 await admin.getByLabel('密码',{exact:true}).fill(env.ADMIN_PASSWORD)
 await admin.getByRole('button',{name:'登录',exact:true}).click()
 const catalog=JSON.parse(fs.readFileSync(path.join(root,'migrations/data/catalog-20260922.json'),'utf8')).models
 await admin.route('**/admin/models',route=>route.fulfill({json:catalog}))
 await admin.getByRole('button',{name:'刷新',exact:true}).click()
 await admin.getByRole('button',{name:'模型管理',exact:true}).click()
 const modelBrowser=admin.getByRole('region',{name:'模型分类管理',exact:true})
 await expect(modelBrowser.getByRole('region',{name:'Anthropic 模型',exact:true})).toBeVisible()
 await expect(modelBrowser.getByRole('region',{name:'OpenAI 模型',exact:true})).toBeVisible()
 await expect(modelBrowser.getByText('gpt-image-2',{exact:true})).toHaveCount(0)
 await admin.getByRole('button',{name:/图像/}).click()
 await expect(modelBrowser.getByText('gpt-image-2',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:/视频/}).click()
 await expect(modelBrowser.getByRole('region',{name:'字节跳动 模型',exact:true})).toBeVisible()
 await admin.getByLabel('搜索模型、公司或渠道').fill('不存在的模型')
 await expect(modelBrowser.getByText('未找到匹配的模型')).toBeVisible()
 await modelBrowser.getByRole('button',{name:'清除搜索'}).click()
 await admin.screenshot({path:path.join(root,'.runtime','model-groups-desktop.png'),fullPage:true})
 await admin.setViewportSize({width:390,height:844})
 if(await admin.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Model browser overflows mobile viewport')
 await admin.screenshot({path:path.join(root,'.runtime','model-groups-mobile.png'),fullPage:true})
 await admin.setViewportSize({width:1440,height:1100})
 await admin.unroute('**/admin/models')
 await admin.getByRole('button',{name:'刷新',exact:true}).click()
 await admin.getByRole('button',{name:'用户与积分',exact:true}).click()
 await admin.getByLabel('企业邮箱前缀',{exact:true}).fill('portal_acceptance')
 await admin.getByLabel('账号月总额度',{exact:true}).fill('1000')
 await admin.getByRole('button',{name:'创建账号',exact:true}).click()
 const initialPassword = await admin.getByLabel('初始密码',{exact:true}).textContent()
 await admin.getByRole('button',{name:'已保存，隐藏密码',exact:true}).click()
 await user.goto('http://127.0.0.1:8194')
 await user.getByRole('button',{name:'企业邮箱登录',exact:true}).click()
 await expect(user.getByRole('button',{name:'创建账号',exact:true})).toHaveCount(0)
 await expect(user.getByText('@star-net.cn',{exact:true})).toBeVisible()
 await user.getByLabel('企业邮箱前缀',{exact:true}).fill('intruder@example.com')
 if(await user.getByLabel('企业邮箱前缀',{exact:true}).evaluate(el=>el.checkValidity()))throw Error('Foreign domain accepted by login field')
 await user.getByLabel('企业邮箱前缀',{exact:true}).fill('portal_acceptance')
 await user.getByLabel('密码',{exact:true}).fill('Wrong-password-123')
 await user.getByRole('button',{name:'登录',exact:true}).click()
 await expect(user.getByRole('alert')).toHaveText('邮箱或密码不正确')
 const errorBox = await user.getByRole('alert').boundingBox()
 const loginBox = await user.getByRole('button',{name:'登录',exact:true}).boundingBox()
 if(errorBox.y + errorBox.height > loginBox.y) throw Error('Login error must be above submit button')
 await user.getByLabel('密码',{exact:true}).fill(initialPassword)
 await user.getByLabel('记住用户名',{exact:true}).check()
 await user.getByRole('button',{name:'登录',exact:true}).click()
 await expect(user.getByRole('heading',{name:'首次登录，请修改密码'})).toBeVisible()
 await expect(user.getByRole('button',{name:'积分账户'})).toHaveCount(0)
 await user.getByLabel('原密码',{exact:true}).fill(initialPassword)
 await user.getByLabel('新密码',{exact:true}).fill('12345678')
 if(await user.getByLabel('新密码',{exact:true}).evaluate(el=>el.checkValidity()))throw Error('Numeric-only password accepted')
 await user.getByLabel('新密码',{exact:true}).fill('Changed8')
 await user.getByLabel('确认新密码',{exact:true}).fill('Changed8')
 await user.getByRole('button',{name:'更新密码',exact:true}).click()
 await expect(user.getByRole('status')).toContainText('密码已更新')
 await user.reload()
 await user.getByRole('button',{name:'企业邮箱登录'}).click()
 await expect(user.getByLabel('企业邮箱前缀',{exact:true})).toHaveValue('portal_acceptance')
 await expect(user.getByLabel('记住用户名',{exact:true})).toBeChecked()
 await expect(user.getByLabel('密码',{exact:true})).toHaveValue('')
 const stored = await user.evaluate(()=>JSON.stringify({...localStorage}))
 if(stored.includes('password') || stored.includes('Changed8') || stored.includes('token'))throw Error('Sensitive credentials persisted')
 await user.getByLabel('记住用户名',{exact:true}).uncheck()
 await user.reload()
 await user.getByRole('button',{name:'企业邮箱登录'}).click()
 await expect(user.getByLabel('企业邮箱前缀',{exact:true})).toHaveValue('')
 await user.getByLabel('企业邮箱前缀',{exact:true}).fill('portal_acceptance')
 await user.getByLabel('密码',{exact:true}).fill('Changed8')
 await user.getByRole('button',{name:'登录',exact:true}).click()
 await expect(user.getByRole('region',{name:'积分账户概览'})).toBeVisible()
 await expect(user.getByText('积分充值',{exact:true})).toHaveCount(0)
 await user.getByRole('button',{name:'API',exact:true}).click()
 await expect(user.getByText('创建第一个 API Key',{exact:true})).toBeVisible()
 await user.getByRole('button',{name:'创建 Key',exact:true}).click()
 await expect(user.getByRole('dialog',{name:'创建 API Key'})).toBeVisible()
 await user.getByLabel('Key 名称',{exact:true}).fill('浏览器验收 Key')
 await user.getByLabel('Key 月消费上限',{exact:true}).fill('1500')
 await user.getByRole('button',{name:'确认创建',exact:true}).click()
 await expect(user.getByRole('region',{name:'新 Key 已创建'})).toBeVisible()
 await user.context().grantPermissions(['clipboard-read','clipboard-write'],{origin:'http://127.0.0.1:8194'})
 const revealedKey=await user.getByLabel('新创建的 API Key',{exact:true}).textContent()
 if(!revealedKey.trim().startsWith('ms_'))throw Error('Created key missing from code card')
 await user.getByRole('button',{name:'复制 Key',exact:true}).click()
 await expect(user.getByRole('button',{name:'复制成功',exact:true})).toBeVisible()
 if((await user.evaluate(()=>navigator.clipboard.readText())).trim()!==revealedKey.trim())throw Error('Copied key differs from revealed key')
 await user.getByRole('region',{name:'新 Key 已创建'}).screenshot({path:path.join(root,'.runtime','key-created.png')})
 await user.getByRole('button',{name:'已保存，隐藏 Key',exact:true}).click()
 await user.getByRole('button',{name:'修改 浏览器验收 Key 月上限',exact:true}).click()
 await expect(user.getByLabel('浏览器验收 Key 月消费上限',{exact:true})).toHaveValue('1500')
 await user.getByLabel('浏览器验收 Key 月消费上限',{exact:true}).fill('1200')
 await user.getByRole('button',{name:'保存月上限',exact:true}).click()
 await expect(user.getByRole('status')).toContainText('Key 月上限已更新')
 await admin.getByLabel('portal_acceptance@star-net.cn 账号月总额度',{exact:true}).fill('1000')
 const quotaResponse=admin.waitForResponse(r=>r.url().includes('/quota')&&r.request().method()==='POST')
 await admin.getByRole('button',{name:'保存总额度',exact:true}).click()
 const savedQuota=await quotaResponse
 if(!savedQuota.ok())throw Error('Quota save failed: '+await savedQuota.text()+' payload '+savedQuota.request().postData())
 await admin.getByRole('button',{name:'模型供应商',exact:true}).click()
 await admin.getByLabel('quote-browser-route并发',{exact:true}).fill('1000')
 await admin.getByRole('button',{name:'保存',exact:true}).click()
 await expect(admin.getByRole('status')).toContainText('配置已保存')
 await expect(admin.getByLabel('quote-browser-route并发',{exact:true})).toHaveValue('1000')

 await admin.getByRole('button',{name:'登记验收',exact:true}).click()
 await admin.getByLabel('验收工单 ID',{exact:true}).fill('missing-fixture-job')
 await admin.getByLabel('验收记录',{exact:true}).fill('Synthetic browser guard test; no model call')
 await admin.getByLabel('已核对请求尺寸、画质、时长等规格',{exact:true}).check()
 await admin.getByLabel('已检查实际产物与请求是否一致',{exact:true}).check()
 await admin.getByLabel('已核对归因和实际用量记录',{exact:true}).check()
 await admin.getByRole('button',{name:'登记验收通过',exact:true}).click()
 await expect(admin.getByRole('alert')).toContainText('successful attributed acceptance job')
 await admin.getByRole('button',{name:'取消验收登记',exact:true}).click()
 await admin.getByRole('button',{name:'配置预估费用',exact:true}).click()
 await admin.getByLabel('默认文本输出 Token',{exact:true}).fill('256')
 await admin.getByLabel('费用调整倍率',{exact:true}).fill('1.25')
 await admin.getByLabel('预估计价规则 JSON',{exact:true}).fill(JSON.stringify([{conditions:{},rates:[{label:'输出',path:'output_tokens',unit:1000000,cny:20}]}]))
 await admin.getByRole('button',{name:'保存预估配置',exact:true}).click()
 await expect(admin.getByRole('status')).toContainText('预估配置已保存')
 await admin.getByRole('button',{name:'配置预估费用',exact:true}).click()
 await expect(admin.getByLabel('默认文本输出 Token',{exact:true})).toHaveValue('256')
 await admin.getByRole('button',{name:'关闭',exact:true}).click()
 await admin.getByRole('button',{name:'生成方式费率',exact:true}).click()
 await admin.getByLabel('模型',{exact:true}).selectOption('gpt-5.6-sol')
 await admin.getByLabel('生成方式',{exact:true}).selectOption('chat')
 await admin.getByLabel('费率来源 / 合同版本').fill('隔离验收数据库虚构费率，仅用于测试')
 await admin.getByLabel('单任务预占积分').fill('50')
 await admin.getByRole('button',{name:'增加计价项'}).click()
 await admin.getByLabel('人民币单价',{exact:true}).fill('2')
 await admin.getByText('确认适用费率并启用此规则',{exact:true}).click()
 await admin.getByRole('button',{name:'发布新版本'}).click()
 await expect(admin.getByText('chat · 全部规格 · 已发布',{exact:true})).toBeVisible()
 command(['-c',`
import asyncio, uuid
from sqlalchemy import select
from gateway.db import Session, Job, Client, Model
from gateway.credits import lock, reserve
from gateway.queue import update
async def main():
 async with Session.begin() as db:
  await lock(db)
  c=await db.scalar(select(Client).where(Client.name=='浏览器验收 Key'))
  m=await db.get(Model,'gpt-5.6-sol')
  j=Job(id='fixture-browser-job',client_id=c.id,user_id=c.user_id,model_id=m.id,kind='chat',channel=m.channel,protocol=m.protocol,payload={'messages':[{'role':'user','content':'Synthetic fixture; no upstream request'}]},request_hash='fixture',idempotency_key='fixture',origin='agent_test',agent_name='code-agent',agent_run_id='portal-browser',test_run_id='portal-browser')
  await reserve(db,c,j,m)
  db.add(j)
 await update('fixture-browser-job',status='succeeded',usage={'completion_tokens':100000})
asyncio.run(main())
`],{PYTHONPATH:path.join(root,'public-api')})
 await user.getByRole('button',{name:'积分账户',exact:true}).click()
 await user.getByRole('button',{name:'刷新积分',exact:true}).click()
 const summary=user.getByRole('region',{name:'积分账户概览'})
 await expect(summary.getByText('980',{exact:true})).toBeVisible()
 await expect(summary.getByText('20',{exact:true})).toBeVisible()
 await expect(user.getByRole('cell').filter({hasText:'月上限调整'}).first()).toBeVisible()
 await user.getByLabel('筛选积分类型').selectOption('task_charge')
 await expect(user.getByRole('region',{name:'积分明细'}).getByRole('row')).toHaveCount(2)
 await user.getByRole('button',{name:'fixture-browser-job',exact:true}).click()
 await expect(user.getByRole('dialog',{name:'任务消费详情'}).getByText('按用量计价')).toBeVisible()
 await user.getByRole('button',{name:'关闭弹窗'}).click()
 await user.getByLabel('筛选积分类型').selectOption('manual_debit')
 await expect(user.getByText('没有符合筛选条件的积分记录')).toBeVisible()
 await user.getByLabel('筛选积分类型').selectOption('')
 await user.getByLabel('每页条数').selectOption('20')
 await expect(user.getByLabel('每页条数')).toHaveValue('20')
 await user.screenshot({path:path.join(root,'.runtime/portal-account.png'),fullPage:true})
 await user.setViewportSize({width:390,height:844})
 if(await user.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Account page overflows mobile')
 await expect(user.getByRole('region',{name:'积分明细'}).locator('.table-wrap')).toHaveJSProperty('scrollWidth',700)
 await user.screenshot({path:path.join(root,'.runtime/portal-account-mobile.png'),fullPage:true})
 await user.getByRole('button',{name:'API',exact:true}).click()
 await user.getByRole('region',{name:'API 模型目录'}).getByRole('button',{name:'文本',exact:true}).click()
 await user.getByRole('region',{name:'API 模型目录'}).getByRole('button',{name:'gpt-5.6-sol',exact:true}).click()
 await expect(user.getByText('200 积分 / 1000000',{exact:true})).toBeVisible()
 await user.getByRole('button',{name:'复制命令',exact:true}).click()
 const commandCopy=await user.evaluate(()=>navigator.clipboard.readText())
 if(!commandCopy.includes('/v1/chat/completions') || commandCopy.includes(revealedKey.trim()))throw Error('Unsafe or incorrect command copy')
 await user.getByRole('button',{name:'复制当前模型文档'}).click()
 if(!(await user.evaluate(()=>navigator.clipboard.readText())).includes('预估费用'))throw Error('Incomplete guide copied')
 await user.getByRole('button',{name:'预估费用',exact:true}).click()
 await expect(user.getByLabel('请求示例代码')).toContainText('estimate_only')
 await user.getByLabel('搜索模型或公司').fill('no-model-match')
 await expect(user.getByText('没有匹配的模型或公司')).toBeVisible()
 await user.getByRole('button',{name:'清除搜索'}).click()
 await user.getByRole('button',{name:'修改 浏览器验收 Key 月上限',exact:true}).click()
 await expect(user.getByRole('dialog',{name:'修改 Key 月上限'})).toBeVisible()
 await user.screenshot({path:path.join(root,'.runtime/portal-key-modal-mobile.png'),fullPage:true})
 await user.getByRole('button',{name:'关闭弹窗'}).click()
 if(await user.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('API page overflows mobile')
 await user.screenshot({path:path.join(root,'.runtime/portal-api-mobile.png'),fullPage:true})
 await user.setViewportSize({width:1440,height:1000})
 await user.screenshot({path:path.join(root,'.runtime/portal-docs.png'),fullPage:true})
 await user.reload()
 await expect(user.getByRole('region',{name:'我的 API Key',exact:true})).toHaveCount(0)
 await expect(user.getByRole('region',{name:'API 模型目录'})).toBeVisible()
 await admin.screenshot({path:path.join(root,'.runtime/admin-pricing.png'),fullPage:true})
 await admin.getByRole('button',{name:'修改密码',exact:true}).click()
 await admin.getByLabel('原密码',{exact:true}).fill(env.ADMIN_PASSWORD)
 await admin.getByLabel('新密码',{exact:true}).fill('AdminNew8')
 await admin.getByLabel('确认新密码',{exact:true}).fill('AdminNew8')
 await admin.getByRole('button',{name:'保存新密码',exact:true}).click()
 await expect(admin.getByRole('status')).toContainText('管理员密码已更新')
 await admin.getByLabel('密码',{exact:true}).fill('AdminNew8')
 await admin.getByRole('button',{name:'登录',exact:true}).click()
 await expect(admin.getByRole('button',{name:'退出登录',exact:true})).toBeVisible()
 if(errors.length)throw Error(errors.join('\n'))
 fs.writeFileSync(path.join(root,'.runtime/portal-browser.json'),JSON.stringify({run,database:dbPath,passed:true,model_calls:0,assertions:['admin account creation','localized login error placement','first password change','self-service keys','two-level monthly limits','mode pricing','measured task charge','private account view','public pricing docs']},null,2))
 console.log('Portal/admin isolated browser acceptance passed; zero model calls')
} finally {
 if(browser)await browser.close()
 for(const p of processes){try{process.kill(-p.pid,'SIGTERM')}catch{}}
}
